export const GET_RECETAS = "GET_RECETAS";
export const GET_RECETAS_POR_NOMBRE = "GET_RECETAS_POR_NOMBRE";
export const GET_TIPOS_DE_DIETA = "GET_TIPOS_DE_DIETA";
export const FILTRAR_POR_TIPO_DE_DIETA = "FILTRAR_POR_TIPO_DE_DIETA";
export const FILTRAR_POR_ORIGEN = "FILTRAR_POR_ORIGEN";
export const ORDENAR_POR_NOMBRE = "ORDENAR_POR_NOMBRE";
export const ORDENAR_POR_PUNTUACION = "ORDER_BY_ATTACK";
export const GET_DETALLES = "GET_DETAIL";
export const RELOAD_RECETAS = "RELOAD_POKEMONS";
export const RESET_DETALLES = "RESET_DETAIL";
export const POST_RECETA = "POST_POKEMON";

//SON LOS NOMBRES DE NUESTRAS ACCIONES 